
#server
server:
  port: 8082


  spring:
      thymeleaf:
          prefix: classpath:templates/
          cleck-template : true
          suffix : .html
          mode : HTML5
          cache : false
          order : 0


